# Generated by Django 5.2.8 on 2026-02-21 10:41

import kmu.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('created', models.DateTimeField(default=kmu.utils.NOW)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('has_profile', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('pseudo_id', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
