# Generated by Django 5.2.8 on 2026-02-21 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('middle_name_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('first_name_en', models.CharField(blank=True, max_length=300, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('org_ru', models.TextField(blank=True, null=True)),
                ('org_en', models.TextField(blank=True, null=True)),
                ('position_ru', models.TextField(blank=True, null=True)),
                ('position_en', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
