# Generated by Django 5.2.8 on 2026-02-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
