# Generated by Django 5.2.8 on 2026-02-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_last_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='has_profile',
        ),
    ]
