# Generated by Django 5.2.8 on 2026-02-22 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.profile'),
        ),
    ]
