# Generated by Django 5.2.8 on 2026-02-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_citizenship_section_alter_participation_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='section',
            name='name_ru',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
