# Generated by Django 5.2.8 on 2026-02-23 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_name_section_name_en_section_name_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='org',
        ),
        migrations.AddField(
            model_name='report',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised', to='users.author'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='online',
            field=models.BooleanField(choices=[(False, 'Очная'), (True, 'Онлайн')], default=False),
        ),
    ]
