# Generated by Django 5.2.8 on 2026-02-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_report_org_report_advisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='org',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='lang',
            field=models.CharField(choices=[('en', 'Английский'), ('ru', 'Русский')], default='en', max_length=3),
        ),
    ]
