# Generated by Django 5.2.8 on 2026-02-23 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_author_email_author_org_alter_report_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='users.report'),
        ),
    ]
