# Generated by Django 5.2.8 on 2026-02-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_author_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='org',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
