# Generated by Django 5.2.8 on 2026-02-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_author_first_name_alter_author_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(default=' ', max_length=300),
            preserve_default=False,
        ),
    ]
