# Generated by Django 5.2.8 on 2026-02-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_report_created_report_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='abstract',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
