# Generated by Django 5.2.8 on 2026-02-25 04:18

import django.db.models.deletion
import kmu.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_report_abstract_alter_report_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=kmu.utils.NOW)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
