# Generated by Django 5.2.8 on 2026-02-25 08:13

import kmu.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_authlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='modified',
            field=models.DateTimeField(default=kmu.utils.NOW),
        ),
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateTimeField(default=kmu.utils.NOW),
        ),
        migrations.AlterField(
            model_name='report',
            name='modified',
            field=models.DateTimeField(default=kmu.utils.NOW),
        ),
    ]
