# Generated by Django 5.2.8 on 2026-02-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_participation_modified_alter_report_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='modified',
            new_name='created',
        ),
    ]
