# Generated by Django 5.2.8 on 2026-02-21 10:42

import landing.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=300)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=landing.models.NOW)),
            ],
        ),
    ]
