citizenships = [
    ["AD", "AD", "Андорра", "Principality of Andorra"],
    ["AE", "AE", "ОАЭ", "United Arab Emirates"],
    ["AF", "AF", "Афганистан", "Islamic Republic of Afghanistan"],
    ["AG", "AG", "Антигуа и Барбуда", "Antigua & Barbuda"],
    ["AL", "AL", "Албания", "Republic of Albania"],
    ["AM", "AM", "Армения", "Republic of Armenia"],
    ["AO", "AO", "Ангола", "Republic of Angola"],
    ["AR", "AR", "Аргентина", "Argentine Republic"],
    ["AS", "AS", "Американское Самоа", "American Samoa"],
    ["AT", "AT", "Австрия", "Republic of Austria"],
    ["AU", "AU", "Австралия", "Australia"],
    ["AX", "AX", "Аландские о-ва", "Åland Islands"],
    ["AZ", "AZ", "Азербайджан", "Republic of Azerbaijan"],
    ["BA", "BA", "Босния и Герцеговина", "Republic of Bosnia and Herzegovina"],
    ["BB", "BB", "Барбадос", "Barbados"],
    ["BD", "BD", "Бангладеш", "People's Republic of Bangladesh"],
    ["BE", "BE", "Бельгия", "Kingdom of Belgium"],
    ["BF", "BF", "Буркина-Фасо", "Burkina Faso"],
    ["BG", "BG", "Болгария", "Republic of Bulgaria"],
    ["BH", "BH", "Бахрейн", "Kingdom of Bahrain"],
    ["BI", "BI", "Бурунди", "Republic of Burundi"],
    ["BJ", "BJ", "Бенин", "Republic of Benin"],
    ["BN", "BN", "Бруней", "Brunei"],
    ["BO", "BO", "Многонациональное Государство Боливия", "Plurinational State of Bolivia"],
    ["BR", "BR", "Бразилия", "Federative Republic of Brazil"],
    ["BS", "BS", "Багамы", "Commonwealth of the Bahamas"],
    ["BT", "BT", "Бутан", "Kingdom of Bhutan"],
    ["BW", "BW", "Ботсвана", "Republic of Botswana"],
    ["BY", "BY", "Беларусь", "Republic of Belarus"],
    ["BZ", "BZ", "Белиз", "Belize"],
    ["CA", "CA", "Канада", "Canada"],
    ["CD", "CD", "Демократическая Республика Конго", "Congo - Kinshasa"],
    ["CF", "CF", "Центрально-Африканская Республика", "Central African Republic"],
    ["CG", "CG", "Конго - Браззавиль", "Republic of the Congo"],
    ["CH", "CH", "Швейцария", "Swiss Confederation"],
    ["CI", "CI", "Кот-д’Ивуар", "Republic of Côte d'Ivoire"],
    ["CL", "CL", "Чили", "Republic of Chile"],
    ["CM", "CM", "Камерун", "Republic of Cameroon"],
    ["CN", "CN", "Китайская Народная Республика", "People's Republic of China"],
    ["CO", "CO", "Колумбия", "Republic of Colombia"],
    ["CR", "CR", "Коста-Рика", "Republic of Costa Rica"],
    ["CU", "CU", "Куба", "Republic of Cuba"],
    ["CV", "CV", "Кабо-Верде", "Republic of Cabo Verde"],
    ["CY", "CY", "Кипр", "Republic of Cyprus"],
    ["CZ", "CZ", "Чехия", "Czech Republic"],
    ["DE", "DE", "Федеративная Республика Германия", "Federal Republic of Germany"],
    ["DJ", "DJ", "Джибути", "Republic of Djibouti"],
    ["DK", "DK", "Дания", "Kingdom of Denmark"],
    ["DM", "DM", "Доминика", "Commonwealth of Dominica"],
    ["DO", "DO", "Доминиканская Республика", "Dominican Republic"],
    ["DZ", "DZ", "Алжир", "People's Democratic Republic of Algeria"],
    ["EC", "EC", "Эквадор", "Republic of Ecuador"],
    ["EE", "EE", "Эстония", "Republic of Estonia"],
    ["EG", "EG", "Египет", "Arab Republic of Egypt"],
    ["ER", "ER", "Эритрея", "the State of Eritrea"],
    ["ES", "ES", "Испания", "Kingdom of Spain"],
    ["ET", "ET", "Эфиопия", "Federal Democratic Republic of Ethiopia"],
    ["FI", "FI", "Финляндия", "Republic of Finland"],
    ["FJ", "FJ", "Фиджи", "Republic of Fiji"],
    ["FM", "FM", "Федеративные Штаты Микронезии", "Federated States of Micronesia"],
    ["FR", "FR", "Франция", "French Republic"],
    ["GA", "GA", "Габон", "Gabonese Republic"],
    ["GB", "GB", "Соединённое Королевство Великобритании и Северной Ирландии", "United Kingdom of Great Britain and Northern Ireland"],
    ["GD", "GD", "Гренада", "Grenada"],
    ["GE", "GE", "Грузия", "Georgia"],
    ["GH", "GH", "Гана", "Republic of Ghana"],
    ["GM", "GM", "Гамбия", "Republic of the Gambia"],
    ["GN", "GN", "Гвинея", "Republic of Guinea"],
    ["GQ", "GQ", "Экваториальная Гвинея", "Republic of Equatorial Guinea"],
    ["GR", "GR", "Греция", "Hellenic Republic"],
    ["GT", "GT", "Гватемала", "Republic of Guatemala"],
    ["GW", "GW", "Гвинея-Бисау", "Republic of Guinea-Bissau"],
    ["GY", "GY", "Гайана", "Republic of Guyana"],
    ["HN", "HN", "Гондурас", "Republic of Honduras"],
    ["HR", "HR", "Хорватия", "Republic of Croatia"],
    ["HT", "HT", "Гаити", "Republic of Haiti"],
    ["HU", "HU", "Венгрия", "Hungary"],
    ["ID", "ID", "Индонезия", "Republic of Indonesia"],
    ["IE", "IE", "Ирландия", "Ireland"],
    ["IL", "IL", "Израиль", "State of Israel"],
    ["IN", "IN", "Индия", "Republic of India"],
    ["IQ", "IQ", "Ирак", "Republic of Iraq"],
    ["IR", "IR", "Исламская Республика Иран", "Islamic Republic of Iran"],
    ["IS", "IS", "Исландия", "Republic of Iceland"],
    ["IT", "IT", "Италия", "Italian Republic"],
    ["JM", "JM", "Ямайка", "Jamaica"],
    ["JO", "JO", "Иордания", "Hashemite Kingdom of Jordan"],
    ["JP", "JP", "Япония", "Japan"],
    ["KE", "KE", "Кения", "Republic of Kenya"],
    ["KG", "KG", "Киргизия", "Kyrgyz Republic"],
    ["KH", "KH", "Камбоджа", "Kingdom of Cambodia"],
    ["KI", "KI", "Кирибати", "Republic of Kiribati"],
    ["KM", "KM", "Коморы", "Union of the Comoros"],
    ["KN", "KN", "Сент-Китс и Невис", "St. Kitts & Nevis"],
    ["KP", "KP", "Корейская Народно-Демократическая Республика", "Democratic People's Republic of Korea"],
    ["KR", "KR", "Республика Корея", "South Korea"],
    ["KW", "KW", "Кувейт", "State of Kuwait"],
    ["KZ", "KZ", "Казахстан", "Republic of Kazakhstan"],
    ["LA", "LA", "Лаосская Народно-Демократическая Республика", "Laos"],
    ["LB", "LB", "Ливан", "Lebanese Republic"],
    ["LC", "LC", "Сент-Люсия", "St. Lucia"],
    ["LI", "LI", "Лихтенштейн", "Principality of Liechtenstein"],
    ["LK", "LK", "Шри-Ланка", "Democratic Socialist Republic of Sri Lanka"],
    ["LR", "LR", "Либерия", "Republic of Liberia"],
    ["LS", "LS", "Лесото", "Kingdom of Lesotho"],
    ["LT", "LT", "Литва", "Republic of Lithuania"],
    ["LU", "LU", "Люксембург", "Grand Duchy of Luxembourg"],
    ["LV", "LV", "Латвия", "Republic of Latvia"],
    ["LY", "LY", "Ливия", "Libya"],
    ["MA", "MA", "Марокко", "Kingdom of Morocco"],
    ["MC", "MC", "Монако", "Principality of Monaco"],
    ["MD", "MD", "Республика Молдова", "Republic of Moldova"],
    ["ME", "ME", "Черногория", "Montenegro"],
    ["MG", "MG", "Мадагаскар", "Republic of Madagascar"],
    ["MH", "MH", "Маршалловы о-ва", "Republic of the Marshall Islands"],
    ["MK", "MK", "Северная Македония", "Republic of North Macedonia"],
    ["ML", "ML", "Мали", "Republic of Mali"],
    ["MM", "MM", "Мьянма (Бирма)", "Republic of Myanmar"],
    ["MN", "MN", "Монголия", "Mongolia"],
    ["MR", "MR", "Мавритания", "Islamic Republic of Mauritania"],
    ["MT", "MT", "Мальта", "Republic of Malta"],
    ["MU", "MU", "Маврикий", "Republic of Mauritius"],
    ["MV", "MV", "Мальдивы", "Republic of Maldives"],
    ["MW", "MW", "Малави", "Republic of Malawi"],
    ["MX", "MX", "Мексика", "United Mexican States"],
    ["MY", "MY", "Малайзия", "Malaysia"],
    ["MZ", "MZ", "Мозамбик", "Republic of Mozambique"],
    ["NA", "NA", "Намибия", "Republic of Namibia"],
    ["NE", "NE", "Нигер", "Republic of the Niger"],
    ["NG", "NG", "Нигерия", "Federal Republic of Nigeria"],
    ["NI", "NI", "Никарагуа", "Republic of Nicaragua"],
    ["NL", "NL", "Нидерланды", "Kingdom of the Netherlands"],
    ["NO", "NO", "Норвегия", "Kingdom of Norway"],
    ["NP", "NP", "Непал", "Federal Democratic Republic of Nepal"],
    ["NR", "NR", "Науру", "Republic of Nauru"],
    ["NZ", "NZ", "Новая Зеландия", "New Zealand"],
    ["OM", "OM", "Оман", "Sultanate of Oman"],
    ["PA", "PA", "Панама", "Republic of Panama"],
    ["PE", "PE", "Перу", "Republic of Peru"],
    ["PF", "PF", "Французская Полинезия", "French Polynesia"],
    ["PG", "PG", "Папуа — Новая Гвинея", "Independent State of Papua New Guinea"],
    ["PH", "PH", "Филиппины", "Republic of the Philippines"],
    ["PK", "PK", "Пакистан", "Islamic Republic of Pakistan"],
    ["PL", "PL", "Польша", "Republic of Poland"],
    ["PS", "PS", "Государство Палестина", "the State of Palestine"],
    ["PT", "PT", "Португалия", "Portuguese Republic"],
    ["PW", "PW", "Палау", "Republic of Palau"],
    ["PY", "PY", "Парагвай", "Republic of Paraguay"],
    ["QA", "QA", "Катар", "State of Qatar"],
    ["RO", "RO", "Румыния", "Romania"],
    ["RS", "RS", "Сербия", "Republic of Serbia"],
    ["RU", "RU", "Российская Федерация", "Russia"],
    ["RW", "RW", "Руанда", "Rwandese Republic"],
    ["SA", "SA", "Саудовская Аравия", "Kingdom of Saudi Arabia"],
    ["SB", "SB", "Соломоновы о-ва", "Solomon Islands"],
    ["SC", "SC", "Сейшельские о-ва", "Republic of Seychelles"],
    ["SD", "SD", "Судан", "Republic of the Sudan"],
    ["SE", "SE", "Швеция", "Kingdom of Sweden"],
    ["SG", "SG", "Сингапур", "Republic of Singapore"],
    ["SI", "SI", "Словения", "Republic of Slovenia"],
    ["SK", "SK", "Словакия", "Slovak Republic"],
    ["SL", "SL", "Сьерра-Леоне", "Republic of Sierra Leone"],
    ["SM", "SM", "Сан-Марино", "Republic of San Marino"],
    ["SN", "SN", "Сенегал", "Republic of Senegal"],
    ["SO", "SO", "Сомали", "Federal Republic of Somalia"],
    ["SR", "SR", "Суринам", "Republic of Suriname"],
    ["SS", "SS", "Южный Судан", "Republic of South Sudan"],
    ["ST", "ST", "Сан-Томе и Принсипи", "Democratic Republic of Sao Tome and Principe"],
    ["SV", "SV", "Сальвадор", "Republic of El Salvador"],
    ["SY", "SY", "Сирийская Арабская Республика", "Syria"],
    ["SZ", "SZ", "Эсватини", "Kingdom of Eswatini"],
    ["TD", "TD", "Чад", "Republic of Chad"],
    ["TG", "TG", "Того", "Togolese Republic"],
    ["TH", "TH", "Таиланд", "Kingdom of Thailand"],
    ["TJ", "TJ", "Таджикистан", "Republic of Tajikistan"],
    ["TL", "TL", "Восточный Тимор", "Democratic Republic of Timor-Leste"],
    ["TM", "TM", "Туркменистан", "Turkmenistan"],
    ["TN", "TN", "Тунис", "Republic of Tunisia"],
    ["TO", "TO", "Тонга", "Kingdom of Tonga"],
    ["TR", "TR", "Турция", "Republic of Türkiye"],
    ["TT", "TT", "Тринидад и Тобаго", "Republic of Trinidad and Tobago"],
    ["TV", "TV", "Тувалу", "Tuvalu"],
    ["TW", "TW", "Тайвань", "Taiwan, Province of China"],
    ["TZ", "TZ", "Объединённая Республика Танзания", "United Republic of Tanzania"],
    ["UA", "UA", "Украина", "Ukraine"],
    ["UG", "UG", "Уганда", "Republic of Uganda"],
    ["US", "US", "Соединённые Штаты Америки", "United States of America"],
    ["UY", "UY", "Уругвай", "Eastern Republic of Uruguay"],
    ["UZ", "UZ", "Узбекистан", "Republic of Uzbekistan"],
    ["VA", "VA", "Государство — город Ватикан", "Vatican City"],
    ["VC", "VC", "Сент-Винсент и Гренадины", "St. Vincent & Grenadines"],
    ["VE", "VE", "Боливарианская Республика Венесуэла", "Bolivarian Republic of Venezuela"],
    ["VN", "VN", "Вьетнам", "Socialist Republic of Viet Nam"],
    ["VU", "VU", "Вануату", "Republic of Vanuatu"],
    ["WS", "WS", "Самоа", "Independent State of Samoa"],
    ["YE", "YE", "Йемен", "Republic of Yemen"],
    ["ZA", "ZA", "Южно-Африканская Республика", "Republic of South Africa"],
    ["ZM", "ZM", "Замбия", "Republic of Zambia"],
    ["ZW", "ZW", "Зимбабве", "Republic of Zimbabwe"]
]
