# Generated by Django 5.2.8 on 2026-03-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='auto',
            field=models.BooleanField(default=False),
        ),
    ]
